### ISSUE TITLE
Uncaught TypeError: classList.contains is not a function

### ISSUE THREAD

**Issue by IiroP** [ApsiV11/sisu-grade-distribution#3]
In `inject_chart.js` file, classList may be either DOMTokenList or (empty) Array:
https://github.com/ApsiV11/sisu-grade-distribution/blob/d0bdaeaba007cbf9cb82e5bcb3dccc7f76e7c32d/scripts/inject_chart.js#L57-L58

However, Array doesn't have `.contains()` method which produces errors in console. The addon seems to work though.
```
inject_chart.js:58 Uncaught TypeError: classList.contains is not a function
    at inject_chart.js:58:30
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (inject_chart.js:54:15)
```

**Comment by aapolaakkio** [comment]
Fix in 80fe9b49fc2276af6ea1c6053af1b166db756297
